"""
PaperTrading Platform - Bot Signal Model
Trading signals and recommendations generated by the assistant bot
"""
from datetime import datetime
from enum import Enum
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Float, Boolean, Text, JSON
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import relationship

from app.db.database import Base


class SignalType(str, Enum):
    """Type of trading signal."""
    TRADE_SUGGESTION = "trade_suggestion"      # Buy/Sell recommendation
    POSITION_ALERT = "position_alert"          # Alert on existing position
    RISK_WARNING = "risk_warning"              # Portfolio risk alert
    MARKET_ALERT = "market_alert"              # Market-wide event
    PRICE_LEVEL = "price_level"                # Key price level reached
    VOLUME_SPIKE = "volume_spike"              # Unusual volume detected
    ML_PREDICTION = "ml_prediction"            # ML model signal
    NEWS_ALERT = "news_alert"                  # News-based alert
    REBALANCE_SUGGESTION = "rebalance_suggestion"  # Portfolio rebalance
    TRAILING_STOP = "trailing_stop"            # Trailing stop adjustment


class SignalPriority(str, Enum):
    """Priority level of signal."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class SignalStatus(str, Enum):
    """Status of a signal."""
    PENDING = "pending"       # Awaiting user action
    ACCEPTED = "accepted"     # User accepted recommendation
    IGNORED = "ignored"       # User dismissed
    EXPIRED = "expired"       # Time-based expiration
    EXECUTED = "executed"     # Action was taken


class SignalDirection(str, Enum):
    """Direction for trade signals."""
    LONG = "long"
    SHORT = "short"
    CLOSE = "close"
    REDUCE = "reduce"
    HOLD = "hold"


class BotSignal(Base):
    """Bot-generated trading signal/recommendation model."""
    
    __tablename__ = "bot_signals"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    portfolio_id = Column(Integer, ForeignKey("portfolios.id", ondelete="SET NULL"), nullable=True)
    
    # Signal identification
    signal_type = Column(SQLEnum(SignalType), nullable=False, index=True)
    priority = Column(SQLEnum(SignalPriority), default=SignalPriority.MEDIUM, nullable=False)
    status = Column(SQLEnum(SignalStatus), default=SignalStatus.PENDING, nullable=False, index=True)
    
    # Symbol info (for trade/position signals)
    symbol = Column(String(20), nullable=True, index=True)
    direction = Column(SQLEnum(SignalDirection), nullable=True)
    
    # Trade suggestion details
    suggested_entry = Column(Float, nullable=True)
    suggested_stop_loss = Column(Float, nullable=True)
    suggested_take_profit = Column(Float, nullable=True)
    suggested_quantity = Column(Integer, nullable=True)
    risk_reward_ratio = Column(Float, nullable=True)
    risk_percent = Column(Float, nullable=True)  # % of portfolio at risk
    
    # Current market data at signal time
    current_price = Column(Float, nullable=True)
    current_volume = Column(Float, nullable=True)
    
    # Signal content
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    rationale = Column(Text, nullable=True)  # Explanation for the signal
    
    # ML/Analysis metadata
    confidence_score = Column(Float, nullable=True)  # 0-100
    ml_model_used = Column(String(50), nullable=True)
    technical_indicators = Column(JSON, nullable=True)  # {"rsi": 65, "macd": "bullish"}
    
    # Source tracking
    source = Column(String(50), nullable=False, default="bot")  # bot, ml, technical, alert
    source_alert_id = Column(Integer, ForeignKey("alerts.id", ondelete="SET NULL"), nullable=True)
    
    # User action tracking
    user_action_at = Column(DateTime, nullable=True)
    user_notes = Column(Text, nullable=True)
    resulting_trade_id = Column(Integer, ForeignKey("trades.id", ondelete="SET NULL"), nullable=True)
    
    # Validity
    valid_until = Column(DateTime, nullable=True)  # Signal expiration
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    user = relationship("User", back_populates="bot_signals")
    portfolio = relationship("Portfolio", back_populates="bot_signals")
    source_alert = relationship("Alert", foreign_keys=[source_alert_id])
    resulting_trade = relationship("Trade", foreign_keys=[resulting_trade_id])
    
    def __repr__(self):
        return f"<BotSignal {self.signal_type.value} {self.symbol or ''} {self.status.value}>"
    
    @property
    def is_actionable(self) -> bool:
        """Check if signal is still actionable."""
        if self.status != SignalStatus.PENDING:
            return False
        if self.valid_until and datetime.utcnow() > self.valid_until:
            return False
        return True
    
    @property
    def is_trade_signal(self) -> bool:
        """Check if this is a trade-related signal."""
        return self.signal_type in [
            SignalType.TRADE_SUGGESTION,
            SignalType.ML_PREDICTION,
            SignalType.TRAILING_STOP
        ]


class BotReport(Base):
    """Bot-generated reports (daily briefing, weekly summary, etc.)."""
    
    __tablename__ = "bot_reports"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # Report type
    report_type = Column(String(50), nullable=False, index=True)  # morning_briefing, daily_summary, weekly_report
    report_date = Column(DateTime, nullable=False, index=True)
    
    # Content
    title = Column(String(200), nullable=False)
    content = Column(JSON, nullable=False)  # Structured report data
    
    # Summary stats (quick access)
    total_signals = Column(Integer, default=0)
    trades_suggested = Column(Integer, default=0)
    alerts_triggered = Column(Integer, default=0)
    
    # Read status
    is_read = Column(Boolean, default=False)
    read_at = Column(DateTime, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    user = relationship("User", back_populates="bot_reports")
    
    def __repr__(self):
        return f"<BotReport {self.report_type} {self.report_date.date()}>"
